### ISSUE TITLE
Awesome but wtf ?? 

### ISSUE THREAD

**Issue by LifeIsStrange** [cvuchener/k90-linux-driver#3]
As I understund this New driver is landed for Linux 4.4 http://phoronix.com/scan.php?page=news_item&px=Linux-4.4-HID-Update
It's the same ? if yes, why create TWO community based drivers for corsair gaming keyboards ?? 
Because it already exist this driver : https://github.com/ccMSC/ckb
You should merge :)

**Comment by cvuchener** [comment]
I am aware of MSC's work and he is aware of mine (I think). The two main reasons for different drivers are:
- There is (currently) nothing to merge. ckb only supports RGB devices. My driver only support the K90 (and the K40 in a dev branch). And there is really nothing in common (except maybe HID usage codes) between non-RGB and RGB protocols.
- The goals are different. The kernel driver supports only basic features: key sending correct key codes, and some basic switches (brightness, playback mode, and current profile for now). User-space driver are best for complex features like LED animations or profile configurations. I have also a [user-space utility for the K90](https://github.com/cvuchener/k90-send-profile).

**Comment by LifeIsStrange** [comment]
"And there is really nothing in common (except maybe HID usage codes) between non-RGB and RGB protocols."
But why ? You have the same finality ! 
" The goals are different." I don't understund, you want to create a simple kernel for basics features and ckb want to be a complex and full featured ? If yes why create a simple driver instead of use and contribute to ckb ? 
And why create a user space utility if the goal is to be basic. 
Sorry for my curiosity :p

**Comment by cvuchener** [comment]
>  But why ? You have the same finality ! 

You could say that to any input device configuration utility. But with nothing in common, merging would bring more complexity without any advantages.

> why create a simple driver instead of use and contribute to ckb ? 

Because I don't think installing something like ckb just for avoiding some wrong key codes is worth it.

> And why create a user space utility if the goal is to be basic. 

I said that to illustrate what I think to be the logical separation between kernel driver and user-space utility. I first thought to integrate that in the kernel but it was adding to much complexity while not following the kernel guidelines. Finally it was much simpler to write a user-space program for this part.

I did not contribute to ckb, because there was nothing to reuse in it. And I don't think MSC is interested either. From the protocol point of view, these devices could be from different vendors.

**Comment by LifeIsStrange** [comment]
Okay I understund thanks ! I wait the MSC opinion and I shut the issue

**Comment by ccMSC** [comment]
Yeah, there are a few reasons why we don't merge them: First, as stated above, we're targeting different devices. While the RGB and non-RGB keyboards are very similar from a user experience point of view, they're vastly different in terms of programming and USB protocol. So the amount of code that could be shared between them is basically zero.

Second, ckb is a user-space driver (meaning it runs as a regular program) as opposed to a kernel driver. The main reason for this is simply because I'm targeting both Linux and OSX, and I _can't_ write a kernel driver for OSX without shelling out $100/yr to Apple for a developer license, which I'm not willing to do. So even though it would be possible to get the driver into kernel space, I don't have any intention of trying it at this time.

Lastly, there's the fact that I don't own any of the non-RGB keyboards and Clement doesn't own any of the RGB ones, so collaboration would be pretty difficult. I can see why you're confused, but from a programming point of view, the two drivers don't really do the same thing.

**Comment by LifeIsStrange** [comment]
Okay thanks for yours answers I was Just curious and now I understund =)
